<?php
require __DIR__ . '/../../includes/db.php';
require __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../includes/helpers.php';
requireLogin();
$user=currentUser();
if (($user['VaiTro'] ?? '') === 'nguoithue') { header('Location: /views/thongbao/index.php'); exit; }
?>
<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Xác nhận hồ sơ</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"><link rel="stylesheet" href="/assets/css/style.css"><style>.proof-thumb{width:112px;height:82px;object-fit:cover;border:1px solid #cbd5e1;border-radius:10px}.request-card{border-left:4px solid #f59e0b}.proof-list{display:flex;gap:14px;flex-wrap:wrap}.proof-list a{font-size:.78rem;color:#475569}.request-actions{display:flex;gap:8px;flex-wrap:wrap}</style></head>
<body><div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-badge"><img src="/assets/pics/logo.webp" class="brand-logo" alt="Logo"></div><div><div class="brand-title">Trọ Tốt</div><div class="brand-subtitle">Management System</div></div></div><div class="user-mini sidebar-top"><img src="<?=htmlspecialchars(getAvatarUrl($user))?>" class="avatar-img" alt="avatar"><div class="user-info"><strong><?=htmlspecialchars($user['HoTen'])?></strong><small><?=htmlspecialchars($user['VaiTro'])?></small></div><a href="/logout.php" class="logout-btn" aria-label="Đăng xuất"><i class="bi bi-box-arrow-right"></i></a></div><nav class="nav-menu"><a class="nav-item" href="/index.php"><i class="bi bi-speedometer2"></i> Dashboard</a><a class="nav-item" href="/views/khu/index.php"><i class="bi bi-buildings"></i> Quản lý phòng thuê</a><a class="nav-item" href="/views/nguoithue/index.php"><i class="bi bi-people"></i> Người thuê</a><a class="nav-item" href="/views/hopdong/index.php"><i class="bi bi-file-earmark-text"></i> Hợp đồng</a><a class="nav-item" href="/views/chisodiennuoc/index.php"><i class="bi bi-lightning-charge"></i> Điện / Nước</a><a class="nav-item" href="/views/hoadon/index.php"><i class="bi bi-receipt"></i> Hóa đơn</a><a class="nav-item active" href="/views/xacnhan/index.php"><i class="bi bi-person-check"></i> Xác nhận hồ sơ</a></nav></aside><main class="main-panel" data-page-title="Xác nhận hồ sơ"><header class="topbar"><div><h2>Xác nhận hồ sơ</h2><p>Kiểm tra ảnh chân dung và giấy tờ định danh trước khi duyệt thay đổi.</p></div></header><section class="card-panel"><div id="requests" class="vstack gap-3"></div></section></main></div>
<div class="modal fade" id="rejectModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" id="rejectForm"><div class="modal-header"><h5 class="modal-title">Từ chối hồ sơ</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label" for="rejectNote">Lý do từ chối</label><textarea id="rejectNote" class="form-control" rows="4" required placeholder="Ví dụ: ảnh CCCD chưa rõ, vui lòng tải lại."></textarea></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Hủy</button><button class="btn btn-danger">Xác nhận từ chối</button></div></form></div></div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="/assets/js/app.js"></script><script>(()=>{const box=document.getElementById('requests'),rejectModal=bootstrap.Modal.getOrCreateInstance(document.getElementById('rejectModal'));let rejectId=0;const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const proof=(url,label)=>url?`<a href="${esc(url)}" target="_blank" rel="noopener"><img class="proof-thumb d-block" src="${esc(url)}" alt="${esc(label)}"><small>${esc(label)}</small></a>`:'';async function load(){const r=await window.app.api('/api/hoso.php');box.innerHTML=(r.data||[]).map(x=>{const d=JSON.parse(x.DuLieu||'{}');return `<article class="request-card border rounded-3 p-3"><div class="d-flex justify-content-between gap-3"><div><h6 class="mb-1">${esc(x.HoTen)} · CCCD ${esc(x.CCCD)}</h6><small class="text-muted">${esc(d.SoDienThoai)} · ${esc(d.Email)}</small><div class="mt-1">${esc(d.DiaChiThuongTru)}</div></div><span class="badge text-bg-warning align-self-start">Chờ xác nhận</span></div><div class="proof-list mt-3">${proof(d.AnhChanDung,'Chân dung')}${proof(d.AnhCCCDMatTruoc,'CCCD trước')}${proof(d.AnhCCCDMatSau,'CCCD sau')}${proof(d.VNeIDMuc2,'VNeID mức 2')}</div><div class="request-actions mt-3"><button class="btn btn-success approve" data-id="${x.Id}"><i class="bi bi-check-lg"></i> Xác nhận</button><button class="btn btn-outline-danger reject" data-id="${x.Id}"><i class="bi bi-x-lg"></i> Từ chối</button></div></article>`}).join('')||'<p class="text-muted mb-0">Không có yêu cầu chờ xác nhận.</p>'}document.addEventListener('click',async e=>{const approve=e.target.closest('.approve'),reject=e.target.closest('.reject');if(approve){await window.app.api('/api/hoso.php?id='+approve.dataset.id,{method:'PUT',body:JSON.stringify({QuyetDinh:'XacNhan'})});load()}if(reject){rejectId=Number(reject.dataset.id);document.getElementById('rejectForm').reset();rejectModal.show()}});document.getElementById('rejectForm').addEventListener('submit',async e=>{e.preventDefault();const note=document.getElementById('rejectNote').value.trim();if(!note)return;await window.app.api('/api/hoso.php?id='+rejectId,{method:'PUT',body:JSON.stringify({QuyetDinh:'TuChoi',GhiChu:note})});rejectModal.hide();load()});load()})();</script></body></html>
