<?php
require __DIR__ . '/../../includes/db.php';
require __DIR__ . '/../../includes/auth.php';
require_once __DIR__ . '/../../includes/navigation.php';
requireLogin();
requireRole(['chutro']);
$user = currentUser();
?>
<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Tài khoản thuê trọ</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"><link rel="stylesheet" href="/assets/css/style.css"><link rel="icon" href="/assets/pics/logo.webp" type="image/webp"></head>
<body><div class="app-shell"><?php renderApplicationSidebar($user, '/views/taikhoanthue/index.php'); ?>
<main class="main-panel"><header class="topbar"><div><h2>Tài khoản thuê trọ</h2><p>Chỉ quản lý tài khoản tại các phòng thuộc khu trọ của bạn.</p></div></header>
<section class="stats-grid">
<div class="stat-card primary"><div class="icon"><i class="bi bi-people"></i></div><div><span>Tổng tài khoản</span><strong id="totalAccounts">0</strong></div></div>
<div class="stat-card success"><div class="icon"><i class="bi bi-person-check"></i></div><div><span>Đang hoạt động</span><strong id="activeAccounts">0</strong></div></div>
<div class="stat-card warning"><div class="icon"><i class="bi bi-person-lock"></i></div><div><span>Đã khóa</span><strong id="lockedAccounts">0</strong></div></div>
</section>
<section class="card-panel mt-4"><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-3"><div><h5 class="mb-1">Danh sách tài khoản</h5><small class="text-muted">Tài khoản người ký hợp đồng và thành viên phòng thuộc quyền quản lý.</small></div><div class="input-group" style="max-width:360px"><span class="input-group-text bg-white"><i class="bi bi-search"></i></span><input id="accountSearch" class="form-control" placeholder="Tìm tên, tài khoản hoặc phòng"></div></div>
<div id="accountMessage" class="alert d-none" role="alert"></div><div class="table-responsive"><table class="table table-modern align-middle" data-mobile-detail-title="Chi tiết tài khoản thuê trọ"><thead><tr><th>Người thuê</th><th>Tên đăng nhập</th><th>Phòng thuộc quản lý</th><th>Liên hệ</th><th>Trạng thái</th><th class="text-end">Thao tác</th></tr></thead><tbody id="accountRows"><tr><td colspan="6" class="text-center text-muted py-4">Đang tải dữ liệu…</td></tr></tbody></table></div></section></main></div>

<div class="modal fade" id="editAccountModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form id="editAccountForm" class="modal-content"><div class="modal-header"><h5 class="modal-title">Sửa tài khoản thuê trọ</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Đóng"></button></div><div class="modal-body row g-3"><input type="hidden" id="editAccountId"><div class="col-12"><label class="form-label" for="editHoTen">Họ tên</label><input id="editHoTen" class="form-control" required></div><div class="col-md-6"><label class="form-label" for="editEmail">Email</label><input id="editEmail" type="email" class="form-control"></div><div class="col-md-6"><label class="form-label" for="editSoDienThoai">Số điện thoại</label><input id="editSoDienThoai" class="form-control"></div><div class="col-12"><label class="form-label">Tên đăng nhập</label><input id="editTenDangNhap" class="form-control" disabled><small class="text-muted">Không thể đổi tên đăng nhập tại đây.</small></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Hủy</button><button class="btn btn-primary">Lưu thay đổi</button></div></form></div></div>

<div class="modal fade" id="passwordModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form id="passwordForm" class="modal-content"><div class="modal-header"><h5 class="modal-title">Cấp lại mật khẩu</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Đóng"></button></div><div class="modal-body"><input type="hidden" id="passwordAccountId"><p class="text-muted">Đặt mật khẩu mới cho <strong id="passwordAccountName"></strong>.</p><label class="form-label" for="newPassword">Mật khẩu mới</label><div class="input-group password-input-group"><input id="newPassword" type="password" class="form-control" minlength="6" autocomplete="new-password" required><button type="button" class="btn password-toggle" id="toggleNewPassword" aria-label="Hiện mật khẩu"><i class="bi bi-eye"></i></button></div><small class="text-muted">Tối thiểu 6 ký tự.</small></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Hủy</button><button class="btn btn-warning">Cấp lại mật khẩu</button></div></form></div></div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="/assets/js/app.js"></script>
<script>(()=>{const host=document.getElementById('accountRows'),search=document.getElementById('accountSearch'),message=document.getElementById('accountMessage'),editModal=bootstrap.Modal.getOrCreateInstance(document.getElementById('editAccountModal')),passwordModal=bootstrap.Modal.getOrCreateInstance(document.getElementById('passwordModal'));let accounts=[];const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),find=id=>accounts.find(x=>Number(x.Id)===Number(id));
function notify(text,type='success'){message.className=`alert alert-${type}`;message.textContent=text;setTimeout(()=>message.classList.add('d-none'),3500)}
function render(){const q=search.value.trim().toLowerCase(),items=accounts.filter(x=>[x.HoTen,x.TenDangNhap,x.Email,x.SoDienThoai,x.DanhSachPhong].join(' ').toLowerCase().includes(q));host.innerHTML=items.map(x=>{const active=Number(x.TrangThai)===1;return `<tr><td><strong>${esc(x.HoTen)}</strong><br><small class="text-muted">#${Number(x.Id)}</small></td><td><code>${esc(x.TenDangNhap)}</code></td><td>${esc(x.DanhSachPhong||'Chưa xác định')}</td><td>${esc(x.SoDienThoai||'—')}<br><small>${esc(x.Email||'—')}</small></td><td><span class="badge ${active?'bg-success':'bg-secondary'}">${active?'Hoạt động':'Đã khóa'}</span></td><td class="text-end text-nowrap"><button class="btn btn-sm btn-outline-primary edit-account" data-id="${x.Id}" title="Sửa"><i class="bi bi-pencil-square"></i></button> <button class="btn btn-sm btn-outline-warning reset-password" data-id="${x.Id}" title="Cấp lại mật khẩu"><i class="bi bi-key"></i></button> <button class="btn btn-sm ${active?'btn-outline-secondary':'btn-outline-success'} toggle-lock" data-id="${x.Id}" title="${active?'Khóa':'Mở khóa'}"><i class="bi ${active?'bi-lock':'bi-unlock'}"></i></button></td></tr>`}).join('')||'<tr><td colspan="6" class="text-center text-muted py-4">Không có tài khoản phù hợp.</td></tr>';totalAccounts.textContent=accounts.length;activeAccounts.textContent=accounts.filter(x=>Number(x.TrangThai)===1).length;lockedAccounts.textContent=accounts.filter(x=>Number(x.TrangThai)!==1).length}
async function load(){try{const r=await app.api('/api/taikhoanthue.php');accounts=r.data||[];render()}catch(e){host.innerHTML=`<tr><td colspan="6" class="text-center text-danger py-4">${esc(e.message)}</td></tr>`}}search.addEventListener('input',render);
document.addEventListener('click',async e=>{const edit=e.target.closest('.edit-account'),reset=e.target.closest('.reset-password'),lock=e.target.closest('.toggle-lock');if(edit){const x=find(edit.dataset.id);if(!x)return;editAccountId.value=x.Id;editHoTen.value=x.HoTen||'';editEmail.value=x.Email||'';editSoDienThoai.value=x.SoDienThoai||'';editTenDangNhap.value=x.TenDangNhap||'';editModal.show()}if(reset){const x=find(reset.dataset.id);if(!x)return;passwordForm.reset();passwordAccountId.value=x.Id;passwordAccountName.textContent=x.HoTen||x.TenDangNhap;passwordModal.show()}if(lock){const x=find(lock.dataset.id);if(!x)return;const next=Number(x.TrangThai)===1?0:1;if(!confirm(`${next?'Mở khóa':'Khóa'} tài khoản ${x.TenDangNhap}?`))return;await app.api(`/api/taikhoanthue.php?id=${x.Id}&action=trangThai`,{method:'PUT',body:JSON.stringify({TrangThai:next})});notify(next?'Đã mở khóa tài khoản.':'Đã khóa tài khoản.');load()}});
editAccountForm.addEventListener('submit',async e=>{e.preventDefault();await app.api(`/api/taikhoanthue.php?id=${editAccountId.value}&action=sua`,{method:'PUT',body:JSON.stringify({HoTen:editHoTen.value,Email:editEmail.value,SoDienThoai:editSoDienThoai.value})});editModal.hide();notify('Đã cập nhật tài khoản.');load()});passwordForm.addEventListener('submit',async e=>{e.preventDefault();await app.api(`/api/taikhoanthue.php?id=${passwordAccountId.value}&action=capLaiMatKhau`,{method:'PUT',body:JSON.stringify({MatKhau:newPassword.value})});passwordModal.hide();notify('Đã cấp lại mật khẩu.')});toggleNewPassword.addEventListener('click',()=>{const visible=newPassword.type==='text';newPassword.type=visible?'password':'text';toggleNewPassword.innerHTML=`<i class="bi ${visible?'bi-eye':'bi-eye-slash'}"></i>`;toggleNewPassword.setAttribute('aria-label',visible?'Hiện mật khẩu':'Ẩn mật khẩu')});load()})();</script></body></html>
