<?php
require __DIR__ . '/../../includes/db.php';
require __DIR__ . '/../../includes/auth.php';
requireLogin(); $user=currentUser();
?>
<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Hợp đồng</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"><link rel="stylesheet" href="/assets/css/style.css"><link rel="icon" href="/assets/pics/logo.webp" type="image/webp"></head><body>
<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-badge"><img src="/assets/pics/logo.webp" class="brand-logo" alt="Logo"></div><div><div class="brand-title">Trọ Tốt</div><div class="brand-subtitle">Management System</div></div></div><?php require_once __DIR__.'/../../includes/helpers.php'; $avatar=getAvatarUrl($user); ?><div class="user-mini sidebar-top"><img src="<?=htmlspecialchars($avatar)?>" class="avatar-img" alt="avatar"><div class="user-info"><strong><?=htmlspecialchars($user['HoTen'])?></strong><small><?=htmlspecialchars($user['VaiTro'])?></small></div><a href="/logout.php" class="logout-btn"><i class="bi bi-box-arrow-right"></i></a></div><nav class="nav-menu"><a class="nav-item" href="/index.php"><i class="bi bi-speedometer2"></i> Dashboard</a><a class="nav-item" href="/views/khu/index.php"><i class="bi bi-buildings"></i> Quản lý phòng thuê</a><a class="nav-item active" href="/views/hopdong/index.php"><i class="bi bi-file-earmark-text"></i> Hợp đồng</a><a class="nav-item" href="/views/chisodiennuoc/index.php"><i class="bi bi-lightning-charge"></i> Điện / Nước</a><a class="nav-item" href="/views/hoadon/index.php"><i class="bi bi-receipt"></i> Hóa đơn</a><a class="nav-item" href="/views/baocao/index.php"><i class="bi bi-bar-chart"></i> Báo cáo</a><a class="nav-item" href="/views/taikhoan/index.php"><i class="bi bi-person-gear"></i> Tài khoản</a></nav></aside>
<main class="main-panel"><header class="topbar"><div><h2>Hợp đồng thuê phòng</h2><p>Hợp đồng được nhóm theo khu, dãy và phòng; mở bản PDF thật để xem hoặc in.</p></div><div class="top-actions"><a href="/views/khu/index.php" class="btn btn-success"><i class="bi bi-key"></i> Cho thuê phòng</a></div></header><section class="card-panel"><div class="row g-2 mb-3"><div class="col-md-6"><input id="contractSearch" class="form-control" placeholder="Tìm phòng, người thuê, khu hoặc dãy..."></div><div class="col-md-3"><select id="contractStatus" class="form-select"><option value="">Tất cả trạng thái</option><option value="DangHieuLuc">Đang hiệu lực</option><option value="GiaHan">Gia hạn</option><option value="HetHan">Hết hạn</option><option value="DaChamDut">Đã chấm dứt</option></select></div></div><div class="table-responsive"><table class="table table-modern align-middle"><thead><tr><th>Khu / dãy / phòng</th><th>Người thuê</th><th>Thời hạn</th><th>Giá thuê</th><th>Trạng thái</th><th></th></tr></thead><tbody id="contractBody"></tbody></table></div></section></main></div>
<script src="/assets/js/app.js"></script><script>
let contracts=[]; const date=v=>{const m=String(v||'').match(/(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}/${m[2]}/${m[1]}`:'—'};
function render(){const q=document.getElementById('contractSearch').value.toLowerCase(), s=document.getElementById('contractStatus').value; const rows=contracts.filter(x=>!s||x.TrangThai===s).filter(x=>[x.TenKhu,x.TenDay,x.SoPhong,x.NguoiThue].join(' ').toLowerCase().includes(q)); const meta=v=>({DangHieuLuc:['Đang hiệu lực','table-success','bg-success'],GiaHan:['Gia hạn','table-primary','bg-primary'],HetHan:['Hết hạn','table-secondary','bg-secondary'],DaChamDut:['Đã chấm dứt','table-danger','bg-danger']}[v]||[v,'','bg-secondary']);document.getElementById('contractBody').innerHTML=rows.map(x=>{const m=meta(x.TrangThai);return `<tr class="${m[1]}"><td><strong>${x.TenKhu}</strong><br><span class="text-muted">${x.TenDay} · Phòng ${x.SoPhong}</span></td><td>${x.NguoiThue}</td><td>${date(x.NgayBatDau)} → ${date(x.NgayKetThuc)}</td><td>${Number(x.GiaThue||0).toLocaleString('en-US')} ₫</td><td><span class="badge ${m[2]}">${m[0]}</span></td><td><button class="btn btn-sm btn-outline-primary open-pdf" data-id="${x.Id}" title="Mở PDF"><i class="bi bi-file-earmark-pdf"></i></button></td></tr>`}).join('')||'<tr><td colspan="6" class="text-muted text-center">Chưa có hợp đồng phù hợp.</td></tr>'}
window.app.api('/api/hopdong.php').then(r=>{contracts=r.data||[];render()}); document.getElementById('contractSearch').addEventListener('input',render);document.getElementById('contractStatus').addEventListener('change',render);document.addEventListener('click',e=>{const b=e.target.closest('.open-pdf');if(b)window.open('/views/hopdong/xem.php?id='+b.dataset.id,'_blank','noopener')});
</script></body></html>
